### PR TITLE
updates to support building on windows

### LINKED ISSUE #253: Can't compile on Windows
Thanks for reporting a bug! Please include all of the following:

```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.0.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.1.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.10.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.11.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.12.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.13.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.14.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.15.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.2.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.3.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.4.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.5.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.6.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.7.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.8.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.difft.2229026d-cgu.9.rcgu.o" "C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.4ucpje1yqf4wo9eh.rcgu.o" "/LIBPATH:C:\\CarTar\\release\\deps" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\difftastic-d0bc0fc173dc38be\\out" "/LIBPATH:C:\\CarTar\\release\\build\\libmimalloc-sys-20c3a23102c37094\\out" "/LIBPATH:C:\\CarTar\\release\\build\\tree-sitter-54819667e45c4a8b\\out" "/LIBPATH:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/WHOLEARCHIVE:tree-sitter-elisp.lib" "/WHOLEARCHIVE:tree-sitter-yaml.lib" "/WHOLEARCHIVE:tree-sitter-gleam.lib" "/WHOLEARCHIVE:tree-sitter-nix.lib" "/WHOLEARCHIVE:tree-sitter-json.lib" "/WHOLEARCHIVE:tree-sitter-java.lib" "/WHOLEARCHIVE:tree-sitter-bash.lib" "/WHOLEARCHIVE:tree-sitter-dart.lib" "/WHOLEARCHIVE:tree-sitter-commonlisp.lib" "/WHOLEARCHIVE:tree-sitter-python.lib" "/WHOLEARCHIVE:tree-sitter-c.lib" "/WHOLEARCHIVE:tree-sitter-elm.lib" "/WHOLEARCHIVE:tree-sitter-tsx.lib" "/WHOLEARCHIVE:tree-sitter-javascript.lib" "/WHOLEARCHIVE:tree-sitter-lua.lib" "/WHOLEARCHIVE:tree-sitter-yaml-cpp.lib" "/WHOLEARCHIVE:tree-sitter-python-cpp.lib" "/WHOLEARCHIVE:tree-sitter-bash-cpp.lib" "/WHOLEARCHIVE:tree-sitter-ocaml-interface.lib" "/WHOLEARCHIVE:tree-sitter-elixir.lib" "/WHOLEARCHIVE:tree-sitter-go.lib" "/WHOLEARCHIVE:tree-sitter-lua-cpp.lib" "/WHOLEARCHIVE:tree-sitter-ocaml.lib" "/WHOLEARCHIVE:tree-sitter-clojure.lib" "/WHOLEARCHIVE:tree-sitter-css.lib" "/WHOLEARCHIVE:tree-sitter-elixir-cpp.lib" "/WHOLEARCHIVE:tree-sitter-cpp.lib" "/WHOLEARCHIVE:tree-sitter-ocaml-interface-cpp.lib" "/WHOLEARCHIVE:tree-sitter-janet-simple.lib" "/WHOLEARCHIVE:tree-sitter-haskell.lib" "/WHOLEARCHIVE:tree-sitter-ocaml-cpp.lib" "/WHOLEARCHIVE:tree-sitter-zig.lib" "/WHOLEARCHIVE:tree-sitter-typescript.lib" "/WHOLEARCHIVE:tree-sitter-cpp-cpp.lib" "/WHOLEARCHIVE:tree-sitter-scala.lib" "/WHOLEARCHIVE:tree-sitter-ruby.lib" "/WHOLEARCHIVE:tree-sitter-rust.lib" "/WHOLEARCHIVE:tree-sitter-c-sharp.lib" "/WHOLEARCHIVE:tree-sitter-php.lib" "/WHOLEARCHIVE:tree-sitter-ruby-cpp.lib" "/WHOLEARCHIVE:tree-sitter-php-cpp.lib" "/WHOLEARCHIVE:tree-sitter-haskell-cpp.lib" "C:\\CarTar\\release\\deps\\libterm_size-a606155b2cf59322.rlib" "C:\\CarTar\\release\\deps\\libwu_diff-25706f2c56b595d3.rlib" "C:\\CarTar\\release\\deps\\libwalkdir-f1e1ee70fbc01ed1.rlib" "C:\\CarTar\\release\\deps\\libsame_file-bc9e1fcdb3a9ce29.rlib" "C:\\CarTar\\release\\deps\\libmimalloc-a34e6c4878df8f00.rlib" "C:\\CarTar\\release\\deps\\liblibmimalloc_sys-5637947aacd9e5d7.rlib" "C:\\CarTar\\release\\deps\\libtree_sitter-218357aeaae69ec2.rlib" "C:\\CarTar\\release\\deps\\libtyped_arena-7014457b2934d18d.rlib" "C:\\CarTar\\release\\deps\\libconst_format-02c2a773f3a8982f.rlib" "C:\\CarTar\\release\\deps\\libclap-181dce83c392cf05.rlib" "C:\\CarTar\\release\\deps\\libtextwrap-15592219c0da512c.rlib" "C:\\CarTar\\release\\deps\\libindexmap-9ba0747720636ee8.rlib" "C:\\CarTar\\release\\deps\\libhashbrown-da79696167b25bce.rlib" "C:\\CarTar\\release\\deps\\libos_str_bytes-866c1ce66d33c507.rlib" "C:\\CarTar\\release\\deps\\libbitflags-fc1965db0469ec95.rlib" "C:\\CarTar\\release\\deps\\libowo_colors-98e60874a82ac78b.rlib" "C:\\CarTar\\release\\deps\\liblazy_static-1ef46232122641ee.rlib" "C:\\CarTar\\release\\deps\\libstrsim-6bb7f88b582d93fe.rlib" "C:\\CarTar\\release\\deps\\librpds-46b113ddf608761e.rlib" "C:\\CarTar\\release\\deps\\libarchery-99a38dcda4cc1b30.rlib" "C:\\CarTar\\release\\deps\\libradix_heap-aeee00374f9c6ec6.rlib" "C:\\CarTar\\release\\deps\\libitertools-f88c3d6a944d7f69.rlib" "C:\\CarTar\\release\\deps\\libeither-e5de8338724a2e66.rlib" "C:\\CarTar\\release\\deps\\librustc_hash-8313ee8ab007b3cf.rlib" "C:\\CarTar\\release\\deps\\libpretty_env_logger-0d1df7f7af835f66.rlib" "C:\\CarTar\\release\\deps\\libenv_logger-0350867492d53208.rlib" "C:\\CarTar\\release\\deps\\libtermcolor-34d3957e6613ab0f.rlib" "C:\\CarTar\\release\\deps\\libwinapi_util-a475941558562532.rlib" "C:\\CarTar\\release\\deps\\libatty-77062c7dfe6818ec.rlib" "C:\\CarTar\\release\\deps\\libwinapi-d5424493765e0873.rlib" "C:\\CarTar\\release\\deps\\libhumantime-ebe0a80c385dc9b7.rlib" "C:\\CarTar\\release\\deps\\libquick_error-6eb9b497be5ca6be.rlib" "C:\\CarTar\\release\\deps\\libregex-c8a7feb7cd5e3697.rlib" "C:\\CarTar\\release\\deps\\libaho_corasick-79387342b0d73800.rlib" "C:\\CarTar\\release\\deps\\libmemchr-76dbfe21baa53138.rlib" "C:\\CarTar\\release\\deps\\libregex_syntax-b2ea96671453d68b.rlib" "C:\\CarTar\\release\\deps\\liblog-533992625f374413.rlib" "C:\\CarTar\\release\\deps\\libcfg_if-d092cf17aa22092c.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-9505d954cc550ca4.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-4368ec34df66b968.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-c4e960482b87deda.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-3e30157661c6e929.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-441bbf33311d8f21.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-a65adc14aa7ec78a.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-754bada3b2f76f43.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-bbc7454d63bcee48.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-083a8721e26e7568.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-fc82f5be4815a343.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-14f675cf009ff7ec.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-39142ba17f25ae37.rlib" "C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-1a5802a39db22341.rlib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\CarTar\\release\\deps\\difft-c8ab8d3c92a269de.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\dschroeder\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note:    Creating library C:\CarTar\release\deps\difft-c8ab8d3c92a269de.lib and object C:\CarTar\release\deps\difft-c8ab8d3c92a269de.exp
          tree-sitter-elm.lib(parser.o) : error LNK2001: unresolved external symbol tree_sitter_elm_external_scanner_create
          tree-sitter-elm.lib(parser.o) : error LNK2001: unresolved external symbol tree_sitter_elm_external_scanner_destroy
          tree-sitter-elm.lib(parser.o) : error LNK2001: unresolved external symbol tree_sitter_elm_external_scanner_scan
          tree-sitter-elm.lib(parser.o) : error LNK2001: unresolved external symbol tree_sitter_elm_external_scanner_serialize
          tree-sitter-elm.lib(parser.o) : error LNK2001: unresolved external symbol tree_sitter_elm_external_scanner_deserialize
          C:\CarTar\release\deps\difft-c8ab8d3c92a269de.exe : fatal error LNK1120: 5 unresolved externals


error: failed to compile `difftastic v0.26.3`, intermediate artifacts can be found at `C:\CarTar`

Caused by:
  could not compile `difftastic` due to previous error
```

### PR DESCRIPTION
**Pull request by fdncred**
closes #253 thanks to @petrochenkov's fix mentioned there.

I just switched the order of a few lines. I did not change any in the build.rs.
The rust-toolchain.toml had to be updated to support this crate which won't compile in 1.56.1 any longer.
```
Caused by:
  package `os_str_bytes v6.2.0` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
```

### CODE REVIEW

**Comment by Wilfred** [comment]
Wonderful, thank you!
